
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.captchaweb.parser;

/** CUP generated class containing symbol constants. */
public class CaptchaParserSym {
  /* terminals */
  public static final int LETIMPAR = 47;
  public static final int TIMES = 79;
  public static final int BOOL = 39;
  public static final int H1 = 16;
  public static final int TYPE = 26;
  public static final int HEX = 54;
  public static final int ROWS = 87;
  public static final int SEMI = 69;
  public static final int ASC = 44;
  public static final int NAME = 28;
  public static final int ROW = 30;
  public static final int ID_ = 59;
  public static final int ALT = 35;
  public static final int RBRACE = 65;
  public static final int RPAREN = 83;
  public static final int INTEGER = 37;
  public static final int LBRACE = 64;
  public static final int LPAREN = 82;
  public static final int NOT = 76;
  public static final int FALSE = 41;
  public static final int PERCNTG = 86;
  public static final int ERROR = 90;
  public static final int DEC = 61;
  public static final int STR = 43;
  public static final int FONTS = 22;
  public static final int WIDTH = 33;
  public static final int REVERSE = 48;
  public static final int INTQ = 56;
  public static final int CLASS = 31;
  public static final int SELECT = 10;
  public static final int FONTF = 23;
  public static final int TRUE = 40;
  public static final int PIXEL = 57;
  public static final int PLUS = 77;
  public static final int QUOTE = 89;
  public static final int DIVIDE = 80;
  public static final int EQUAL = 84;
  public static final int COLS = 29;
  public static final int FONTF_VALUE = 88;
  public static final int ALIGN = 24;
  public static final int DECIMAL = 38;
  public static final int CHAR = 42;
  public static final int LETPAR = 46;
  public static final int INPUT = 8;
  public static final int ALING_VALUE = 25;
  public static final int TXTAREA = 9;
  public static final int GCIC = 2;
  public static final int PERCENTG = 58;
  public static final int GREATER = 62;
  public static final int DIV = 12;
  public static final int INT = 60;
  public static final int URL = 81;
  public static final int EQEQ = 70;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int SMLLREQ = 73;
  public static final int BUTTON = 15;
  public static final int PARAGRAPH = 17;
  public static final int GRTREQ = 72;
  public static final int SPAM = 7;
  public static final int MINUS = 78;
  public static final int SCRIPT = 18;
  public static final int SRC = 32;
  public static final int BODY = 6;
  public static final int HREF = 19;
  public static final int TITLE = 4;
  public static final int OR = 74;
  public static final int error = 1;
  public static final int EXIT = 52;
  public static final int BCKGRND = 20;
  public static final int DESC = 45;
  public static final int ID = 27;
  public static final int CLICK = 36;
  public static final int COLOR = 21;
  public static final int HEAD = 3;
  public static final int ALERT = 51;
  public static final int COLON = 68;
  public static final int IMG = 13;
  public static final int RANDOM_N = 50;
  public static final int HEIGHT = 34;
  public static final int BR = 14;
  public static final int RBRACKET = 67;
  public static final int GLOBAL = 53;
  public static final int OPTION = 11;
  public static final int STRING = 85;
  public static final int COLOUR = 55;
  public static final int RANDOM_C = 49;
  public static final int SMALLER = 63;
  public static final int NEQ = 71;
  public static final int AND = 75;
  public static final int LBRACKET = 66;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "PARAGRAPH",
  "SCRIPT",
  "HREF",
  "BCKGRND",
  "COLOR",
  "FONTS",
  "FONTF",
  "ALIGN",
  "ALING_VALUE",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROW",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "CLICK",
  "INTEGER",
  "DECIMAL",
  "BOOL",
  "TRUE",
  "FALSE",
  "CHAR",
  "STR",
  "ASC",
  "DESC",
  "LETPAR",
  "LETIMPAR",
  "REVERSE",
  "RANDOM_C",
  "RANDOM_N",
  "ALERT",
  "EXIT",
  "GLOBAL",
  "HEX",
  "COLOUR",
  "INTQ",
  "PIXEL",
  "PERCENTG",
  "ID_",
  "INT",
  "DEC",
  "GREATER",
  "SMALLER",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "SEMI",
  "EQEQ",
  "NEQ",
  "GRTREQ",
  "SMLLREQ",
  "OR",
  "AND",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "URL",
  "LPAREN",
  "RPAREN",
  "EQUAL",
  "STRING",
  "PERCNTG",
  "ROWS",
  "FONTF_VALUE",
  "QUOTE",
  "ERROR"
  };
}

